### ISSUE TITLE
I can't use OStatus

### ISSUE THREAD

**Issue by lascapi** [pfefferle/wordpress-ostatus#7]
Hello,
I try to use Ostatus for connect my Wordpress with my Mastodon account. 

I install all dependencies (5 plugins) and ... I don't understand the next step ? 
Maybe i'm blind ... 
Maybe a little tutorial is needed here ?  

Thank's for your work :-)

**Comment by pfefferle** [comment]
Should be working now with the latest versions of the OStauts and PubSubHubbub/WebSub plugins...

**Comment by poVoq** [comment]
I think the problem is that even after installing all the related plugins, there seems to be no actual (visible) functionality on the site? Is it a purely hidden function that let's you connect via GNUSocial/Mastodon?
What would be the connection address for your blog then? I tried the plain wordpress URL in Hubzilla (theoretically GNUSocial and Mastodon compatible) but it isn't connecting either...

**Comment by pfefferle** [comment]
I will add some more details about the identifier you can use. Try `@loginname@example.com` or `https://example.com/author/autor-slug`.

**Comment by poVoq** [comment]
How about a small notice above the comment section on how to connect?

**Comment by pfefferle** [comment]
Can you tell me the exact identifier so that I can have a look?

**Comment by mediaformat** [comment]
Sure, it is @sionnach@urbanwildlife.biz

**Comment by pfefferle** [comment]
I tried it on mastodon.social and I can follow your account...

You should disable the ActivityPub plugin for now, because it is not yet fully functional and that's why you can't see the posts. I would recommend to only use OStatus for now.

**Comment by mediaformat** [comment]
I had tried searching on a smaller, perhaps not-up-date instance. Search does indeed work on mastodon.social
Thanks
